# Generated by Django 4.2.18 on 2025-02-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('times_requested', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
