# Generated by Django 4.2.17 on 2025-02-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0002_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField(unique=True)),
                ('needed_points', models.PositiveIntegerField(default=0)),
                ('valid_grade_a', models.PositiveIntegerField(default=0)),
                ('valid_grade_bc', models.PositiveIntegerField(default=0)),
                ('equity_held', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='mlmuser',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
