# Generated by Django 4.2.17 on 2025-03-02 11:40

from django.db import migrations, models
import mlm.models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0004_level_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmuser',
            name='referral_code',
            field=models.CharField(default=mlm.models.generate_referral_code, max_length=6, unique=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
