# Generated by Django 4.2.17 on 2025-03-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0005_alter_mlmuser_referral_code_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='required_direct',
        ),
        migrations.RemoveField(
            model_name='level',
            name='required_indirect',
        ),
        migrations.RemoveField(
            model_name='mlmuser',
            name='points',
        ),
        migrations.AddField(
            model_name='level',
            name='needed_a',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='needed_bc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='nft_reservation_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='nft_reservation_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlmuser',
            name='active_a_referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mlmuser',
            name='active_bc_referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mlmuser',
            name='nft_reservation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='level',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='mlmuser',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
