# Generated by Django 4.2.17 on 2025-03-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0006_remove_level_required_direct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmuser',
            name='active_a_referrals',
        ),
        migrations.RemoveField(
            model_name='mlmuser',
            name='active_bc_referrals',
        ),
    ]
